### ISSUE TITLE
Having a tough time figuring out how to work with an array

### ISSUE THREAD

**Issue by chrisjohnson** [rafamel/yaml-import#12]
I've got an array of objects that I want to import and merge (to use as a sort of "extend base" config). Here's roughly what it looks like:

```yaml
name: rx1
values:
  - key: app_id
    value: rx1
  - key: foo
    value: 1
  - key: bar
    value: 2
```

So what I want is to move y and z into another file and import them. I've tried the following combinations (their respective output is as follows) with no luck:

foo.yml
```yaml
name: rx1
values: !!import/payload
  paths: _testing.base
  strategy: deep
  data:
    - key: app_id
      value: rx1
```

_testing.base
```yaml
values:
  - key: foo
    value: 1
  - key: bar
    value: 2
```

result
```javascript
{
    name: "rx1",
    values: {
        values: [{
                key: "foo",
                value: 1
            },
            {
                key: "bar",
                value: 2
            }
        ],
        key: "app_id",
        value: "rx1"
    }
}
```

-----

foo.yml
```yaml
name: rx1
values: !!import/payload
  paths: _testing.base
  strategy: deep
  data:
    - key: app_id
      value: rx1
```

_testing.base
```yaml
- key: foo
  value: 1
- key: bar
  value: 2
```

result
```javascript
{
    name: "rx1",
    values: {
      key: "app_id",
      value: "rx1"
    }
  }
```

-----

foo.yml
```yaml
name: rx1
!!import/payload
  paths: _testing.base
  strategy: deep
  data:
    values:
      - key: app_id
        value: rx1
```

_testing.base
```yaml
values:
  - key: foo
    value: 1
  - key: bar
    value: 2
```

result
```
{ YAMLException: unknown tag !<tag:yaml.org,2002:import/payload> at line 3, column 8:
      paths: _testing.base
           ^
    at generateError (./node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
    at throwError (./node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
    at composeNode (./node_modules/js-yaml/lib/js-yaml/loader.js:1428:7)
    at readBlockMapping (./node_modules/js-yaml/lib/js-yaml/loader.js:1036:16)
    at composeNode (./node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
    at readDocument (./node_modules/js-yaml/lib/js-yaml/loader.js:1519:3)
    at loadDocuments (./node_modules/js-yaml/lib/js-yaml/loader.js:1575:5)
    at load (./node_modules/js-yaml/lib/js-yaml/loader.js:1596:19)
    at Object.safeLoad (./node_modules/js-yaml/lib/js-yaml/loader.js:1618:10)
    at loadEnvironments (./lib/environment-helpers.js:19:25)
  name: 'YAMLException',
  reason: 'unknown tag !<tag:yaml.org,2002:import/payload>',
  mark:
   Mark {
     name: null,
     buffer:
      'name: rx1\n!!import/payload\n  paths: _testing.base\n  strategy: deep\n  data:\n    values:\n      - key: app_id\n        value: rx1\n\u0000',
     position: 34,
     line: 2,
     column: 7 },
  message:
   'unknown tag !<tag:yaml.org,2002:import/payload> at line 3, column 8:\n      paths: _testing.base\n           ^' }
```

I'm not sure if there's a bug or if I'm just not understanding how to use this correctly. Would you mind taking a gander for me?

**Comment by chrisjohnson** [comment]
Oh, I think I got it. Seems like I need to an extra layer of array to get it to know that I want them to merge:

foo.yml
```yaml
name: rx1
values: !!import/payload
  paths: _testing.base
  strategy: deep
  data:
    -
      - key: app_id
        value: rx1
```

_testing.base
```yaml
- key: foo
  value: 1
- key: bar
  value: 2
```

result
```javascript
{
    name: "rx1",
    values: [      {
        key: "foo",
        value: 1
      },
      {
        key: "bar",
        value: 2
      },
      {
        key: "app_id",
        value: "rx1"
      }    ]
  }
```

**Comment by rafamel** [comment]
Hi Chris! Thanks for reporting. This was actually a bug on how the concat was handled for additional data. A new release has been published with a fix!

**Comment by chrisjohnson** [comment]
Just so I'm understanding, which of the 3 use cases in my original post were the correct approach that had a bug? I tried the last one and I still see the exact same result with yaml-import 2.0.0

**Comment by rafamel** [comment]
The correct approach would be:

root.yml:
```
name: rx1
values: !!import/payload
  paths: foo.yml
  strategy: deep
  data:
    - key: app_id
      value: rx1
```

foo.yml
```
- key: foo
  value: 1
- key: bar
  value: 2
```

**Comment by rafamel** [comment]
Forgot to mention, the error you got is to be expected, as you're importing within an object, but without a key in the example that you got the error in -the data is malformed.

**Comment by chrisjohnson** [comment]
I'm still getting strange results. This might warrant a second ticket, let me know if you want me to move the details to a new one.

The example you give works just fine, but when I change the `value` values from numbers to strings, suddenly it merges the arrays in a weird way:

root.yml
```yaml
name: rx1
values: !!import/payload
  paths: foo.yml
  strategy: deep
  data:
    - key: app_id
      value: rx1
```

foo.yml
```yaml
- key: foo
  value: a
- key: bar
  value: b
```

result
```javascript
{
    name: "rx2",
    values: [{
            key: "foo",
            value: "a"
        },
        {
            key: "bar",
            value: "b"
        },
        [{
                key: "app_id",
                value: "rx2"
            },
            {
                key: "sudo_key",
                value: "rxservice-testing-rx2"
            }
        ]
    ]
}
```

If either `value` is a number, it produces the expected results
