### ISSUE TITLE
Feature: import file alongside keys

### ISSUE THREAD

**Issue by Lakitna** [rafamel/yaml-import#2]
## Current situation
I am using `yaml-import` to aggregate OpenAPI files and I keep running into a situation where I have to split my `yml`s in a lot of small pieces to make it import correctly. 

Doing this results in a lot of very small files that don't always make sense from a content point of view.

```yml
# foo.yml
foo:
  type: string
fizz:
  type: string
buzz:
  type: string
```

```yml
# bar.yml
bar:
  type: number
```

```yml
# base.yml
base:
  type: object
  properties:
    !!import/merge [
      './foo.yml',
      './bar.yml',
    ]
```

```yml
# output
base:
  type: object
  properties:
    foo:
      type: string
    fizz:
      type: string
    buzz:
      type: string
    bar:
      type: number
```

## Desired situation

Instead, I would like to be able to do something like below. This gets rid of the splintered file `bar.yml`.

```yml
# base.yml
base:
  type: object
  properties:
    !!import/single './foo.yml'
    bar:
      type: number
```

```yml
# output
base:
  type: object
  properties:
    foo:
      type: string
    fizz:
      type: string
    buzz:
      type: string
    bar:
      type: number
```

In my situation, there should never be a name conflict, but I think it would be best to allow a conflicting key to overwrite the existing one.

**Comment by rafamel** [comment]
Hey Sander, I'm packed at the moment so this is not something I'll address immediately. Also, I'm not a 100% sure the proposed api is feasible, but I think a solution could be found. If you can do a PR, that would definitely speed things up. In the meantime, keep in mind you can just use straight up js to merge objects as you wish to create OpenAPI specs.

**Comment by Lakitna** [comment]
No problem, the workaround is annoying but workable.

Since I've committed to doing everything in `yml` files there is not really a way to simply merge objects anymore. Even though I've limited myself here I still think that was the right choice.

I don't mind trying to write this myself. I would appreciate it if you can point me in the right direction.

**Comment by rafamel** [comment]
This has been implemented via `!!import/payload`. The new version has been published as a beta prerelease to ease up the transition, as the whole import api has been redesigned. Give it a try and let me know! ;)

**Comment by Lakitna** [comment]
Awesome! I'll upgrade later this week to see if the current imports still do the same thing, and if `!!import/payload` works as expected.

**Comment by Lakitna** [comment]
I've tried the new version and it works great. The 'old' commands continue to work as expected and `!!import/payload` allows me to simplify things.

The following even works without a hitch

```yaml
foo:
  !!import/payload
    path: ./some/file/path.yml
    data:
      bar:
        !!import/single another/file/path.yml
```

It gives me a lot more freedom, I love it!

Thanks for the upgrade
